# coding: utf-8

"""
    Киноконтент API

    REST API биржи описаний к фильмам и сериалам https://kinocontent.club  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_edit_user(self):
        """Test case for edit_user

        Редактирование пользователя  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Получение информации о пользователе  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
