# coding: utf-8

"""
    Киноконтент API

    REST API биржи описаний к фильмам и сериалам https://kinocontent.club  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.task_api import TaskApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_task(self):
        """Test case for add_task

        Добавление задания  # noqa: E501
        """
        pass

    def test_delete_task(self):
        """Test case for delete_task

        Удаление задания  # noqa: E501
        """
        pass

    def test_edit_task(self):
        """Test case for edit_task

        Редактирование задания  # noqa: E501
        """
        pass

    def test_get_task(self):
        """Test case for get_task

        Получение информации о задании  # noqa: E501
        """
        pass

    def test_get_tasks(self):
        """Test case for get_tasks

        Получение списка заданий  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
