# coding: utf-8

"""
    Киноконтент API

    REST API биржи описаний к фильмам и сериалам https://kinocontent.club  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.task_api import TaskApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_task_delete(self):
        """Test case for task_delete

        Удаление задания  # noqa: E501
        """
        pass

    def test_task_get(self):
        """Test case for task_get

        Получение информации о задании  # noqa: E501
        """
        pass

    def test_task_post(self):
        """Test case for task_post

        Добавление задания  # noqa: E501
        """
        pass

    def test_task_put(self):
        """Test case for task_put

        Редактирование задания  # noqa: E501
        """
        pass

    def test_tasks_get(self):
        """Test case for tasks_get

        Получение списка заданий  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
