<?php
/**
 * TaskApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Киноконтент API
 *
 * API биржи описаний к фильмам и сериалам https://kinocontent.club
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TaskApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TaskApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for taskDelete
     *
     * Удаление задания.
     *
     */
    public function testTaskDelete()
    {
    }

    /**
     * Test case for taskGet
     *
     * Получение информации о задании.
     *
     */
    public function testTaskGet()
    {
    }

    /**
     * Test case for taskPost
     *
     * Добавление задания.
     *
     */
    public function testTaskPost()
    {
    }

    /**
     * Test case for taskPut
     *
     * Редактирование задания.
     *
     */
    public function testTaskPut()
    {
    }

    /**
     * Test case for tasksGet
     *
     * Получение списка заданий.
     *
     */
    public function testTasksGet()
    {
    }
}
